import type { Metadata } from "next";
import "./globals.css";
import { inter } from "@/components/plan/common/fonts";
import Script from "next/script";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Script
        src={`https://oapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NEXT_PUBLIC_NAVER_MAPS_API_KEY}&submodules=geocoder`}
        strategy="beforeInteractive"
        />
        {children}
      </body>
    </html>
  );
}
